### ISSUE TITLE
Dynamic Scenes

### ISSUE THREAD

**Issue by wrboyce** [wrboyce/hueman#1]
@danlane pointed out it would be nice to be able to define a scene without knowing which/how many bulbs it will apply to, for example:

```
    scenes:
      sunset:
        orange:
          quantity: 20%
          priority: 80 
          hue: 46789
          sat: 150
        yellows:
          quantity: 60%
          priority: 90
          hue: 23133
          sat: 200
        reds:
          quantity: 10%
          priority: 70
          hue: 0
          sat: 200
```

[One Idea](https://gist.github.com/anonymous/eec096db0c89830f75c5).
